### ISSUE TITLE
implement basic voting screen

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#1]
Bounty template:
Simple voting screen with input field to enter voice credits and a submit button. Once the button is clicked and the user has sufficient voice credits the voice credits should be deducted from the users accounts and converted into votes at a quadratic rate and submitted into the [voting booth contract](https://github.com/project-democracy/voting-contracts/blob/master/contracts/VotingBooth.sol) of the proposal. 

![image](https://user-images.githubusercontent.com/45236782/62624372-3377e480-b923-11e9-88e5-c54a6bbd3fe9.png)

## Scope
- input validation (checking voice credit balance)
- confirmation once transaction was submitted successfully
- error screen if transaction failed
- construct and send valid vote transaction
- display votes, based on voice credits in input field, at a quadratic rate
- if votes has been casted already, then allow increase

## Deliverables
- code
- unit tests

## Roles
bounty gardener: @MaxKuck  / 10%
bounty worker: @MaxStalker  / 70%
bounty reviewer: @johannbarbie  / 20%

**Comment by johba37** [comment]
paid out here: https://leapdao.slack.com/archives/CHBFMQ526/p1567432136007900
