### ISSUE TITLE
Create UI to Cast vote

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/voting-frontend#10]
## Scope
- Transformation of the Burner Wallet User Interface to the DEORAxVOLT Interface to Cast Vote

## Deliverables
- User Interface to Cast a Vote (https://xd.adobe.com/spec/2bc5e6f1-589f-4724-6275-73449bd3ddaa-5df4/)
- public deployment  to mvp.deora.earth

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: @MaxStalker   / 70%
bounty reviewer: name / 20%

**Comment by MaxKaay** [comment]
isn't volt.deora.earth ?

**Comment by johba37** [comment]
closed in favor of https://github.com/deora-earth/voting-frontend/issues/12
