### ISSUE TITLE
 Main page UI

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#11]
## Scope
Changing buner wallet UI into the new interface of the volt voting platform
- list view - ID + title + submitted votes on each proposal
- sorting function (ID number, number of votes, favorites)
- filter function (6 topics - Smart State / Economic Renaissance / Social Equality / Global Balance / Citizen Empowerment / EU Reform) 
- search function (title and number)

## Deliverables
- User Interface of mvp (https://xd.adobe.com/spec/2bc5e6f1-589f-4724-6275-73449bd3ddaa-5df4/)

- public deployment  to volt.deora.earth

## Roles
bounty gardener: @MaxKuck   / 5%
bounty worker: @MaxStalker   / 80%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
@MaxStalker can we finish delivery of https://github.com/deora-earth/voting-frontend/issues/1 and https://github.com/deora-earth/voting-frontend/issues/2 before you assign yourself to new issues?

**Comment by MaxStalker** [comment]
@johannbarbie I had a blocker with both #1 and #2 and provided delicate nature of approaching deadline, I thought I could finish front-end stuff, which still need to be done.

I finished most of this task, so please don't remove my assignment from this one ^__^

**Comment by johba37** [comment]
ok, but can you create pull requests for the other issues? so we can see any progress?

**Comment by MaxStalker** [comment]
@sunify introduced some needed changes to UI here https://github.com/deora-earth/voting-frontend/pull/24 and here https://github.com/deora-earth/voting-frontend/pull/36

**Comment by MaxStalker** [comment]
@MaxKuck can you check if everything is implemented, so we could close this?
Also add @johannbarbie and @troggy to reviewer role - they were checking @sunify PR code.

**Comment by MaxKaay** [comment]
+ Need to be sorted by ID (not name) / I think this was actually working with the other proposals for the volt congress (but the naming is confusing - that's why changing it to `ID` )
+ Search function for the topics need to included (sort function and bar is missing, but to compensate time for more urgent issues - just adding it to search parameter should be fine for now)
![image](https://user-images.githubusercontent.com/45236782/64381302-2984f680-d033-11e9-9ced-fc38a3497b54.png)

**Comment by MaxKaay** [comment]
Sorting function for casted votes is not working
