### ISSUE TITLE
proposal view

### ISSUE THREAD

**Issue by johba37** [deora-earth/voting-frontend#12]
## Scope

create a view for each of the ~50 proposals that will exist to vote on during the congress. the proposals can be read as JSON from https://www.npoint.io/docs/217ecb17f01746799a3b. each porposal contains a `description` property, which holds text. the text should be displayed according to the formatting and colors. 

There are mockups here: https://xd.adobe.com/spec/2bc5e6f1-589f-4724-6275-73449bd3ddaa-5df4/

## Deliverables
- [x] a screen for each proposal
- [x] vote button on the bottom
- [x] pop-up of vote controls when vote button clicked
- [ ] progress screen after submission
- [ ] receipt screen after submission
- [x] rendered version of the BBcode description

## Roles
bounty gardener: @johannbarbie   / 10%
bounty worker: @sunify  / 75%
bounty reviewer: @troggy / @johannbarbie  / 15%

**Comment by MaxStalker** [comment]
@sunify please, check this branch: 
https://github.com/deora-earth/voting-frontend/tree/feature/basic-vote-screen
There's a lot of stuff already implemented.
Would be cool if we could sync on how to deliver this.
