### ISSUE TITLE
vote history and timer

### ISSUE THREAD

**Issue by johba37** [deora-earth/voting-frontend#13]
## **Remove main page / list view footer of voice history and timer (the view is otherwise too small)**

Changing buner wallet UI into the new interface of the volt voting platform:

## Scope
- voting history (three recent voting transactions - proposal ID and number of votes casted)
- timer with left timing - see JSON from Johann: https://www.npoint.io/docs/217ecb17f01746799a3b

## Deliverables
- User Interface of mvp (https://xd.adobe.com/spec/2bc5e6f1-589f-4724-6275-73449bd3ddaa-5df4/)

- public deployment  to volt.deora.earth

## Roles
bounty gardener: @MaxKuck   / 5%
bounty worker: @MaxStalker   / 80%
bounty reviewer: name / 15%

**Comment by MaxKaay** [comment]
updated: Remove main page / list view footer of voice history and timer (the view is otherwise too small)
