### ISSUE TITLE
Error when sending all voice credit at once 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#135]
![image](https://user-images.githubusercontent.com/45236782/64472720-15401700-d163-11e9-8d9c-e1b2771b60b3.png)

**Comment by johba37** [comment]
resolved through airdropping more VOT
![Screen Shot 2019-09-07 at 12 22 50](https://user-images.githubusercontent.com/659301/64473702-4d972380-d16a-11e9-9a30-cf29f1a0c839.png)
