### ISSUE TITLE
Create Result Page script

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#15]
Adding result interface of the voting stats

## Scope
- only needed once all votes are casted no updated during the voting process
- script should iterate over each proposal and read the balances of yes and no box contracts
- ranking consists of total votes and votes casted for either yes or no as displayed in the mockup
- ranked by the highest amount of votes (beneath the rank)

## Deliverables
- create a script to generate a HTML file. This HTML then shows the results defined under scope

- mockup: 
<img width="361" alt="Bildschirmfoto 2019-09-02 um 18 08 57" src="https://user-images.githubusercontent.com/43147663/64126207-3395c380-cdad-11e9-8b0d-27f2e15e8a81.png">

## Roles
bounty gardener: @MaxKuck   / 5%
bounty worker:    / 80%
bounty reviewer: name / 15%

**Comment by MaxKaay** [comment]
@MaxStalker ? :)

**Comment by MaxStalker** [comment]
@MaxKuck I guess anyone can pick htis one up. Or I can do it, when I finish the rest of the stuff :)

**Comment by MaxStalker** [comment]
@MaxKuck Can you tell me what we have on the left hand side?

**Comment by MaxKaay** [comment]
@MaxStalker on the left we have on top the ranking number and beneath the total number of votes that were casted under the specific proposal

**Comment by MaxStalker** [comment]
ah, right :)
it's just those two "1"s at the end that was confusing

**Comment by MaxKaay** [comment]
Update: only needed once the voting are casted, not during the voting itself

**Comment by sunify** [comment]
Not finished yet
