### ISSUE TITLE
hype EthTurin with QV

### ISSUE THREAD

**Issue by johba37** [deora-earth/voting-frontend#150]
# Bounty

Deora sponsors EthTurin. explain what we do + QV + track. 

## Scope
- content related to QV and EthTurin.
- announce the talk with Giovani.
- why use QV for hackathons?

## Deliverables
- twitter posts 
- talk with Giovani (how qv helps governance)

## Roles
bounty gardener: name / share  
bounty worker: name / share  
bounty reviewer: name / share

**Comment by ghost** [comment]
post content, possible themes:
* what is qv?
* how is it helpful?

mention in talk:
* give basic voting instructions, how the app works

**Comment by johba37** [comment]
- [ ] ask ethTurin for conversion from referrer

**Comment by ghost** [comment]
first tweet posted:

https://twitter.com/deora_earth/status/1252253242559467520

**Comment by ghost** [comment]
second tweet posted:
https://twitter.com/deora_earth/status/1252631509992902656
