### ISSUE TITLE
remove hardcoded history

### ISSUE THREAD

**Issue by johba37** [deora-earth/voting-frontend#19]
![image](https://user-images.githubusercontent.com/659301/64251706-678df780-cf19-11e9-89e9-7aa01670655f.png)

**Comment by MaxStalker** [comment]
I believe, this is part of the #13 , which is not finished atm

**Comment by MaxKaay** [comment]
yes, it's part of the #13

**Comment by johba37** [comment]
done here: https://github.com/deora-earth/voting-frontend/pull/115
