### ISSUE TITLE
implement basic vote withdrawal 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#2]
Bounty template:
Enabling to change number of casted votes by sending a withdrawal transaction. Realisation via input field that allows a number between 0 and the previously casted votes on the proposal. Pressing the submit button will send the quadratic votes to the trash bins and return the voice credits to the user.

![image](https://user-images.githubusercontent.com/45236782/62623589-7fc22500-b921-11e9-95ed-c1c95cf5c5c4.png)

## Scope
- input validation (number between 0 and the previously casted votes)
- building and sending the transaction
- success screen if transaction included 
- error screen if transaction failed

## Deliverables
- code
- unit tests

## Roles
bounty gardener: @MaxKuck   / 10%
bounty worker: @MaxStalker  / 70%
bounty reviewer: @johannbarbie  / 20%

**Comment by MaxStalker** [comment]
Implemented in #14 and #84
