### ISSUE TITLE
no need to enable vote controls when balance 0

### ISSUE THREAD

**Issue by johba37** [deora-earth/voting-frontend#26]
![Screenshot_20190904-155049](https://user-images.githubusercontent.com/659301/64276672-c61e9a00-cf48-11e9-9c32-6da4f868eeb3.jpg)

**Comment by MaxStalker** [comment]
Controls should be different, yes.
If you voted previously on specific proposal it should have withdraw button there. If no - then we need some message that you can't vote with 0 credits.
Though solution should go from design side. 
@MaxKuck @simonweniger can you provide your input on this?

**Comment by MaxKaay** [comment]
@MaxStalker @simonweniger I think the easiest way would be to just grey out the yes/no button. If message is easy to implement, then we should go for: "Keine Voice Credits verfügbar" if someone wants to click yes/no or use the slider
