### ISSUE TITLE
Wrong Interface/list view on iPhone 6 - Safari Browser 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#27]
![IMG_8655](https://user-images.githubusercontent.com/45236782/64326293-0114e200-cfca-11e9-8ea9-198b877886bb.PNG)

**Comment by simonweniger** [comment]
Same Problem on the iphone xs (opera, safari & chromr)

**Comment by MaxStalker** [comment]
Fixed in #36
