### ISSUE TITLE
Create continues deployment for voting-frontend

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/voting-frontend#4]
## Scope
- the masterbatches and all PR's should be deployed by travis

## Deliverables
- travis configuration
- public deployment @mvp.deora.earth 

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: @iamonuwa, @johannbarbie    / 50%, 20%
bounty reviewer: @johannbarbie / 20%

**Comment by johba37** [comment]
the S3 bucket is called `volt.deora.earth` and the cloudfront distribution id is `E11AR1A1T4EJQY`.

**Comment by johba37** [comment]
https://travis-ci.org/deora-earth/voting-frontend/builds/577273858
<img width="808" alt="Screen Shot 2019-08-27 at 2 31 16 PM" src="https://user-images.githubusercontent.com/659301/63771443-73edd100-c8d7-11e9-8e76-05e3d513fa28.png">

**Comment by iamonuwa** [comment]
Am fixing this now

**Comment by simonweniger** [comment]
Everything fine @johannbarbie can I close the Issue ?

**Comment by johba37** [comment]
resolved here: https://github.com/deora-earth/voting-frontend/pull/8
