### ISSUE TITLE
fixed header

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#5]
## Scope
- developing a fixed header with display of voice credits available and total. Displaying profile like in the burner wallet. Adding burger menu button on the top right. 

## Deliverables
![image](https://user-images.githubusercontent.com/45236782/63530160-38818a00-c506-11e9-8e19-ce6c42754348.png)

 

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: @MaxStalker  / 70%
bounty reviewer: @johannbarbie   / 20%

**Comment by MaxStalker** [comment]
@MaxKuck here's some inspiration for you ;)
https://codepen.io/MaxStalker/pen/ExYZKJQ

**Comment by MaxStalker** [comment]
@simonweniger do you think we can close this one?
Also, add @johannbarbie to reviewer role, so he can get his share of bounty
