### ISSUE TITLE
Error: local Storage and balance card out of sync: .....

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/voting-frontend#67]
![image](https://user-images.githubusercontent.com/43147663/64371885-f38b4680-d021-11e9-81f5-11e62e86338d.png)

**Comment by troggy** [comment]
happens because of partial withdrawals.. temporary workaround is to disable partial withdrawals. Done here: #116

Related: https://github.com/deora-earth/voting-contracts/pull/15
