### ISSUE TITLE
Solution to Open and End Voting

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#7]
### Open Question

The official debate needs to be closed and finished before the voting on the platform can be opened. While open it also needs to be closed, preferably with a timer solution to make everyone aware of the time limit.

![image](https://user-images.githubusercontent.com/45236782/63719927-57f21d00-c84e-11e9-99cf-6f2b8853f9be.png)

### First ideas
Front-end solution:
greying out the vote button and not allowing anyone to submit a vote. 

![image](https://user-images.githubusercontent.com/45236782/63719966-6b9d8380-c84e-11e9-8d97-77b4a0645f23.png)

**Comment by johba37** [comment]
i've included `startTime` and `endTime` in the JSON:
```
{
  "voteStartTime": "2019-09-08T18:25:43.511Z",
  "voteEndTime": "2019-09-09T18:25:43.511Z",
  "proposals": [
    {
      "proposalId": "prop-12",
      "title": "bla",
      "description": "bla bla bla",
      "topic": [
        "Smart State",
        "Social Equality"
      ],
      "boothAddress": "0x1ba5dca50564df62f60a4930635f7dbbf38378b7",
      "yesBoxAddress": "0xdea3f5922b9bbde4707d1f73d4d265040c49282b",
      "noBoxAddress": "0x772e6c04dcb3b42d716db90699de6664f4ba45ba"
    }
  ]
}
```
which you can pull from: `https://api.npoint.io/217ecb17f01746799a3b`

@MaxStalker will this do to enable what we want?

**Comment by johba37** [comment]
implemented
