### ISSUE TITLE
New withdraw screen: change the screen that shows up after you withdrawed your vote

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/voting-frontend#74]
You find the Icon assets here: 
https://we.tl/t-RpvWhdnc3x

![Loading - Send Vote – 1](https://user-images.githubusercontent.com/43147663/64374971-339ff880-d025-11e9-8a8e-9bf5d07de64b.png)

**Comment by MaxStalker** [comment]
Please, provide that arrow as SVG or PNG image.

**Comment by simonweniger** [comment]
Sure, you can donwload the arrow here 👍 

https://we.tl/t-RpvWhdnc3x

**Comment by johba37** [comment]
resolved here: https://github.com/deora-earth/voting-frontend/pull/117
