### ISSUE TITLE
User should be able to click the yes/no buttons multiple times to increse the vote 

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/voting-frontend#78]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43147663/64385854-d82b3600-d037-11e9-8c49-880de467f024.gif)

**Comment by MaxStalker** [comment]
@simonweniger what if he press "YES" two times and them press "NO" will it count as single "NO" or 3 "NO" votes? :)

**Comment by simonweniger** [comment]
I think it than should go back to 1 vote :)
