### ISSUE TITLE
can NOT withdraw from NO vote. Screen hangs

### ISSUE THREAD

**Issue by johba37** [deora-earth/voting-frontend#90]
![Screenshot_20190906-110359__01](https://user-images.githubusercontent.com/659301/64416054-bca34800-d096-11e9-9934-f2f9738a87c1.jpg)

## how to reproduce
1. go to any proposal
2. vote on NO
3. go back to main screen
4. open same proposal again
5. try to wridraw

**Comment by troggy** [comment]
via #84
