### ISSUE TITLE
Updating the menu view + adding new menu point + updating pages behind menu points

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/voting-frontend#97]
- Adding new menu point `Weitere Anträge` and putting this on the second last position (see ranking of next point)

- updating the placeholder pages with the following links:
Über uns: https://www.deora.earth/volt-platform/about
Quadratical Voting: https://www.deora.earth/volt-platform/quadratic
Die Blockchain: https://www.deora.earth/volt-platform/blockchain
Sicherheit & Privacy: https://www.deora.earth/volt-platform/privacy
Weitere Anträge: https://www.deora.earth/volt-platform/extra-proposals
Wahlergebnisse: https://www.volt.deora.earth/results

- Menu view needs to be adjusted (made responsive).
Current behaviour, overlapping menu points.

![image](https://user-images.githubusercontent.com/45236782/64429554-92fa1900-d0b6-11e9-9bc8-2d5589a1e9d1.png)

**Comment by MaxKaay** [comment]
@MaxStalker

**Comment by MaxStalker** [comment]
@MaxKuck All links lead to 404 :\
